header: null
names:
  - 'No'
  - '神姫名'
  - 'ひらがな'
  - '属性'
  - 'タイプ'
  - 'HP1'
  - 'Attack1'
  - 'HP2'
  - 'Attack2'
  - 'エピソード数'
  - 'プロフィール1'
  - 'プロフィール2'
  - 'アビリティ1'
  - '効果1'
  - '使用間隔1'
  - '効果時間1'
  - 'アビリティ2'
  - '効果2'
  - '使用間隔2'
  - '効果時間2'
  - 'アビリティ3'
  - '効果3'
  - '使用間隔3'
  - '効果時間3'
  - 'アビリティ4'
  - '効果4'
  - '使用間隔4'
  - '効果時間4'
  - 'エピソード1'
  - 'あらすじ1'
  - '内容1'
  - 'タグ1'
  - 'エピソード2'
  - 'あらすじ2'
  - '内容2'
  - 'タグ2'
  - 'エピソード3'
  - 'あらすじ3'
  - '内容3'
  - 'タグ3'
  - 'HTML1'
  - 'HTML設定先1'
  - 'HTML2'
  - 'HTML設定先2'
  - '取得フラグ'
skipRows: 4
sortBy:
  - 'ひらがな'
  - 'No'
ascending:
  - True
  - True
