conditions:
  loseless: True
  quality: 80
  targetExtensions:
    - 'jpg'
    - 'jpeg'
    - 'png'
input:
  path: 'temp'
  recursive: False
  replace: False
  delete: False
output:
  path: 'temp'
  extension: 'webp'
