inputs:
  - path: '~/Documents/神姫エピソ－ドメモ管理帳.xlsx'
    conditions:
      - sheet           : 'SSR神姫リスト'
        rarity          : 'SSR'
        additionalRarity: ''
        convertedName   : 'SSR'
      - sheet           : '期間限定SSR神姫リスト'
        rarity          : 'SSR'
        additionalRarity: 'Limited'
        convertedName   : '期間限定SSR'
      - sheet           : 'イベントSR神姫リスト'
        rarity          : 'SR'
        additionalRarity: 'Event'
        convertedName   : 'イベントSR'
      - sheet           : 'SR神姫リスト'
        rarity          : 'SR'
        additionalRarity: ''
        convertedName   : 'SR'
      - sheet           : '期間限定SR神姫リスト'
        rarity          : 'SR'
        additionalRarity: 'Limited'
        convertedName   : '期間限定SR'
      - sheet           : '特典SR神姫リスト'
        rarity          : 'SR'
        additionalRarity: 'Privilege'
        convertedName   : '特典SR'
      - sheet           : 'R神姫リスト'
        rarity          : 'R'
        additionalRarity: ''
        convertedName   : 'R'
      - sheet           : '期間限定R神姫リスト'
        rarity          : 'R'
        additionalRarity: 'Limited'
        convertedName   : '期間限定R'
      - sheet           : 'スキンリスト'
        rarity          : 'Skin'
        additionalRarity: ''
        convertedName   : 'スキン'
output:
  destination: 'temp'
  prefix:      ''
  suffix:      ''
  extension:   'html'
