excel2csv:
    - excel: C:/Users/angelmaneuver/PycharmProjects/converter/excel/神姫エピソ－ドメモ管理帳.xlsx
      csv:
          - sheet: SSR神姫リスト→CSV出力用
          - sheet: 期間限定SSR神姫リスト→CSV出力用
          - sheet: イベントSR神姫リスト→CSV出力用
          - sheet: SR神姫リスト→CSV出力用
          - sheet: 期間限定SR神姫リスト→CSV出力用
          - sheet: 特典SR神姫リスト→CSV出力用
          - sheet: R神姫リスト→CSV出力用
          - sheet: 期間限定R神姫リスト→CSV出力用

csv2translation:
  header: <table class="kamihime-list"><thead><tr><th class="kamihime-No">No.</th><th class="kamihime-name">神姫名</th><th class="kamihime-attribute">属性</th><th class="kamihime-type">タイプ</th><th class="kamihime-status">Max HP/ATK</th><th colspan="2">エピソ－ド</th></tr></thead><tbody>
  footer: </tbody></table>
  target:
    - sheet: SSR神姫リスト→CSV出力用
      out: SSR.html
      parameter:
        rarity: ssr
    - sheet: 期間限定SSR神姫リスト→CSV出力用
      out: SSR期間限定.html
      parameter:
        rarity: ssr
    - sheet: イベントSR神姫リスト→CSV出力用
      out: SRイベント配布.html
      parameter:
        rarity: sr
    - sheet: SR神姫リスト→CSV出力用
      out: SR.html
      parameter:
        rarity: sr
    - sheet: 期間限定SR神姫リスト→CSV出力用
      out: SR期間限定.html
      parameter:
        rarity: sr
    - sheet: 特典SR神姫リスト→CSV出力用
      out: SR特典.html
      parameter:
        rarity: sr
    - sheet: R神姫リスト→CSV出力用
      out: R.html
      parameter:
        rarity: r
    - sheet: 期間限定R神姫リスト→CSV出力用
      out: R期間限定.html
      parameter:
        rarity: r