name: Converter CI

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - run: cd ${{github.workspace}}
    - run: pip install pipenv
    - run: pipenv --python ${{ matrix.python-version }}
    - run: pipenv install --dev
    - run: pipenv run python3 test/runTest.py
      if: runner.os != 'Windows'
    - run: pipenv run python3 test\runTest.py
      if: runner.os == 'Windows'
