name: Converter CI

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install pipenv
    - run: pipenv --python ${{ matrix.python-version }}
    - run: pipenv install --dev
    - run: pipenv run python3 test/runTest.py
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - run: pip install pipenv
    - run: pipenv --python 3.9
    - run: pipenv install --dev
    - run: pipenv run coverage run --branch --source=src test/runTest.py
    - run: pipenv run coverage report
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: c11d4780357bedb6b295c2b87779718a786bc58b0a58c4b903df974502bc7980
      with:
        coverageCommand: pipenv run coverage xml
        coverageLocations: ${{github.workspace}}/coverage.xml:coverage.py
